providers:
  discord:
    enabled: true
    webhookURL: "https://discordapp.com/api/webhooks/{webhook.id}/{webhook.token}"
  yammer:
    enabled: true
    APIURL: https://webhook.site/7dc6cf29-c27c-4683-860d-08fd587a608d
    groupID: 123456
    token: somesecrettext
